spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test
    username: sa
    password:
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure : error
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
